<a href="https://colab.research.google.com/github/Selinavcii/MachineLearningCodes/blob/main/numpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy-Numerical Python

Advantages Of Numpy Arrays:
 1. Allows several mathematical operations
 2. Faster Operations

In [1]:
import numpy as np

list vs numpy- time taken

In [2]:
from time import process_time

time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time=process_time()

python_list = [i +5 for i in python_list]

end_time= process_time()

print(end_time-start_time)

0.00171864899999985


time taken by a numpy array

In [5]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array+=5

end_time= process_time()

print(end_time-start_time)


0.000501470000000559


Lists-numpy arrays

In [7]:
#list

list1=[1,2,3,4,5,6]

print(list1)

type(list1)

[1, 2, 3, 4, 5, 6]


list

In [8]:
#numpy array

np_array=np.array([1,2,3,4,5,6])

print(np_array)

type(np_array)

[1 2 3 4 5 6]


numpy.ndarray

In [11]:
# creating a 1 dim array

a=np.array([1,2,3,4])

print(a)

a.shape # 4 column

[1 2 3 4]


(4,)

In [12]:
#creating a 2 dim array

b=np.array([(1,2,3,4),(5,6,7,8)])

print(b)

b.shape # 2 row, 4 column

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [13]:
c= np.array([(1,2,3,4),(5,6,7,8)],dtype=float)

print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [14]:
#create a numpy array of Zeros

x=np.zeros((4,5))

print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# create a numpy array of a particular value

y=np.full((5,4),7)

print(y)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [17]:
#create a numpy array with random values

b=np.random.random((3,4))

print(b)

[[0.85158377 0.40173277 0.69075316 0.76802255]
 [0.44819805 0.92205202 0.13395927 0.80419651]
 [0.67407902 0.24553068 0.10961387 0.85891387]]


In [19]:
#create random integer  values numpy array with a specific range

c=np.random.randint(10,100,(3,5))  # values must be 10 to 100 , array must be 3 row 5 column

print(c)


[[76 49 49 34 70]
 [23 52 27 85 96]
 [97 80 17 58 72]]


In [20]:
# create a numpy array of evenly spaced values

d=np.linspace(10,30,6) # between 10 to 30, the increase amount is 6

print(d)


[10. 14. 18. 22. 26. 30.]


In [23]:
# convert a list to a numpy array

list2 = [ 10,20,20,20,50]

np_array=np.asarray(list2)

print("List:",list2 )

print("Numpy array:",np_array)



List: [10, 20, 20, 20, 50]
Numpy array: [10 20 20 20 50]


numpy.ndarray

Mathematical operations on a np array

In [24]:
list1=[1,2,3,4,5]

list2=[5,6,7,8,9,10]

print(list1 + list2) # concatenate or joins two list

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10]


In [27]:
a = np.random.randint(0,10,(3,3))

b = np.random.randint(10,20,(3,3))

print(a)

print(b)

print(a+b) # add the values with each other


[[1 1 1]
 [5 2 6]
 [3 0 8]]
[[12 11 19]
 [13 13 12]
 [13 18 14]]
[[13 12 20]
 [18 15 18]
 [16 18 22]]


Array Manipulation

In [36]:
array= np.random.randint(0,10,(2,3))

print("array")

print(array)

print(array.shape)

#transpose

print("transposed array")

trans= np.transpose(array)

print(trans)

print(trans.shape)

array
[[5 9 3]
 [0 7 3]]
(2, 3)
transposed array
[[5 0]
 [9 7]
 [3 3]]
(3, 2)


[[0 6]
 [4 8]
 [2 3]]
(3, 2)


In [35]:
# reshaping an array

a= np.random.randint(0,10,(2,3))

print("a")

print(a)

print(a.shape)

print("b")

b= a .reshape(3,2)

print(b)

print(b.shape)





a
[[4 1 9]
 [0 9 8]]
(2, 3)
b
[[4 1]
 [9 0]
 [9 8]]
(3, 2)


[[1 1]
 [3 5]
 [0 1]]
(3, 2)
